---
- ansible.builtin.include_tasks: utils/check_file_exists.yml
  vars:
    path_to_file: "{{ downstream_galaxy_yml }}"

- ansible.builtin.set_fact:
    upstream_downstream_collections_map:
      - { upstream_name: 'redhat_csp_download', downstream_name: 'redhat_csp_download' }
      - { upstream_name: 'jws', downstream_name: 'jws' }
      - { upstream_name: 'wildfly', downstream_name: 'jboss_eap' }
      - { upstream_name: 'infinispan', downstream_name: 'jboss_data_grid' }
      - { upstream_name: 'keycloak', downstream_name: 'rh_sso' }

- ansible.builtin.include_tasks: utils/rename_vars_in_file.yml
  vars:
    path_to_file: "{{ downstream_galaxy_yml }}"
    upstream_value: "{{ upstream_namespace }}.{{ item.upstream_name }}"
    downstream_value: "{{ downstream_namespace }}.{{ item.downstream_name }}"
  loop: "{{ upstream_downstream_collections_map }}"
