---
- ansible.builtin.assert:
    that:
      - downstream_galaxy_yml is defined
    quiet: True
    fail_msg: "Required parameter is missing."

- name: "Load metadata on galaxy.yml: {{ downstream_galaxy_yml }}."
  ansible.builtin.stat:
    path: "{{ downstream_galaxy_yml }}"
  register: is_downstream_galaxy_yml

- name: "Ensures provided path exists and is a directory."
  assert:
    that:
      - is_downstream_galaxy_yml is defined
      - is_downstream_galaxy_yml.stat is defined
      - is_downstream_galaxy_yml.stat.exists is defined
      - is_downstream_galaxy_yml.stat.exists
    quiet: True
    fail_msg: "Invalid path to galaxy.yml provided: {{ downstream_galaxy_yml }}"

- ansible.builtin.set_fact:
    upstream_downstream_collections_map:
      - { upstream_name: 'redhat_csp_download', downstream_name: 'redhat_csp_download' }
      - { upstream_name: 'jws', downstream_name: 'jws' }
      - { upstream_name: 'wildfly', downstream_name: 'jboss_eap' }
      - { upstream_name: 'infinispan', downstream_name: 'jboss_data_grid' }
      - { upstream_name: 'keycloak', downstream_name: 'rh_sso' }

- ansible.builtin.include_tasks: utils/rename_vars_in_file.yml
  vars:
    path_to_file: "{{ downstream_galaxy_yml }}"
    upstream_value: "{{ item.upstream_name }}"
    downstream_value: "{{ item.downstream_name }}"
  loop: "{{ upstream_downstream_collections_map }}"
