---
- ansible.builtin.include_tasks: utils/check_file_exists.yml

- ansible.builtin.set_fact:
    upstream_downstream_collections_map:
      - { upstream_name: 'redhat_csp_download', downstream_name: 'redhat_csp_download' }
      - { upstream_name: 'jws', downstream_name: 'jws' }
      - { upstream_name: 'wildfly', downstream_name: 'eap' }
      - { upstream_name: 'infinispan', downstream_name: 'data_grid' }
      - { upstream_name: 'keycloak', downstream_name: 'sso' }
      - { upstream_name: 'amq', downstream_name: 'amq_broker' }
      - { upstream_name: 'amq_streams', downstream_name: 'amq_streams' }
      - { upstream_name: 'common', downstream_name: 'runtimes_common' }

- ansible.builtin.include_tasks: utils/rename_vars_in_file.yml
  vars:
    upstream_value: "{{ upstream_namespace }}.{{ replacement.upstream_name }}"
    downstream_value: "{{ downstream_namespace }}.{{ replacement.downstream_name }}"
  loop: "{{ upstream_downstream_collections_map }}"
  loop_control:
    loop_var: replacement
