---
- name: "Checks that required parameters have been provided"
  ansible.builtin.assert:
    that:
      - path_role_folder is defined
      - upstream_name is defined
      - downstream_name is defined
    quiet: true
    fail_msg: "Missing required parameters (path to role)"

- name: "Find all YAML files (.yml)  and Jinja templates (.j2) contained in role {{ path_role_folder }}"
  ansible.builtin.find:
    paths: "{{ path_role_folder }}"
    patterns: '*.yml,*.j2'
    recurse: yes
  register: all_files_to_update

- ansible.builtin.set_fact:
    list_files_to_edit: []

- ansible.builtin.set_fact:
    list_files_to_edit: "{{ list_files_to_edit + [ file_to_update.path ] }}"
  loop: "{{ all_files_to_update.files }}"
  loop_control:
    loop_var: file_to_update


- ansible.builtin.assert:
    that:
      - list_files_to_edit is defined
      - list_files_to_edit | length > 0
    quiet: true
    fail_msg: "No file found in role folder {{ path_role_folder }}."

- name: "List all files to be edit while processing role {{ path_role_folder }}:"
  ansible.builtin.debug:
    var: list_files_to_edit

- name: "Rename vars in main.yml in vars,defaults and meta"
  ansible.builtin.include_tasks: rename_vars_in_file.yml
  loop: "{{ list_files_to_edit }}"
  loop_control:
    loop_var: path_to_file
