---
- name: "Janus transformation process"
  hosts: localhost
  gather_facts: no
  vars:
    upstream_namespace:  "middleware_automation"
    downstream_namespace: "redhat"
    workdir: "{{ lookup('env', 'PWD') }}"
    upstream_projects_dir: "{{ workdir }}/upstream"
    downstream_projects_dir: "{{ workdir }}/downstream"
    skip_setup: True
  pre_tasks:
    - name: "Determine full path to project folder (if not provided)."
      ansible.builtin.set_fact:
        project_root_folder: "{{ lookup('env', 'PWD') }}/upstream/{{ upstream_name }}.git"
      when:
        - not project_root_folder is defined
        - upstream_name is defined

    - name: "Git clone {{ project_git_url }} into {{ project_root_folder }}"
      ansible.builtin.git:
        repo: "{{ project_git_url }}"
        dest: "{{ project_root_folder }}"
        version: "{{ project_git_version | default(omit) }}"
      when:
        - project_root_folder is defined
        - project_git_url is defined
  tasks:
    - name: "Run Janus."
      ansible.builtin.include_role:
        name: janus
  post_tasks:
    - name: "Build collection for {{ downstream_name }}"
      command: ansible-galaxy collection build .
      args:
        chdir: "{{ downstream_project }}"
        #creates: too
