---
- name: "Checks that required parameters have been provided"
  ansible.builtin.assert:
    that:
      - path_to_file is defined
      - upstream_name is defined
      - downstream_name is defined
    quiet: true
    fail_msg: "Missing required parameters (path to role)"

- name: "Load metadata for file to edit {{ path_to_file  }}"
  ansible.builtin.stat:
    path: "{{ path_to_file }}"
  register: is_path_to_file

- name: "Check that metadata for {{ path_to_file }} has been loaded"
  ansible.builtin.assert:
    that:
        - is_path_to_file is defined
        - is_path_to_file.stat is defined
    quiet: true
    fail_msg: "Can't load metada for {{ path_to_file }}"

- block:
    - name: "Update all reference to upstream {{ upstream_name }} to downstream {{ downstream_name }}"
      ansible.builtin.replace:
        path: "{{ path_to_file }}"
        regexp: "{{ upstream_name }}_(.*$)"
        replace: "{{ downstream_name }}_\\1"
        #validate: "python -c 'import yaml, sys; print(yaml.safe_load(sys.stdin))'"
  when:
    - is_path_to_file.stat.exists

- name: "Info msg"
  ansible.builtin.debug:
    msg: "No file {{ path_to_file }}"
  when:
    - not is_defaults_yml.stat.exists is defined or not is_defaults_yml.stat.exists
