---
- assert:
    that:
      - root_folder is defined
    quiet: true
    fail_msg: "Missing required path to root_folder"

- name: "List all playbooks in tasks from role: {{ root_folder }}"
  ansible.builtin.find:
    paths: "{{ root_folder }}"
    recurse: yes
      #    use_regex: yes
  register: yml_files

- ansible.builtin.include_tasks: rename_vars_in_file.yml
  vars:
    path_to_file: "{{ yml_file.path }}"
  loop: "{{ yml_files.files }}"
  loop_control:
    loop_var: yml_file
