---
- ansible.builtin.assert:
    that:
      - downstream_collection_name is defined
    quiet: true

- ansible.builtin.debug:
    msg: "Switch defaults to downstream for playbook {{ path_to_playbook_file }} of collection {{ downstream_collection_name }}."

- ansible.builtin.include_tasks: utils/rename_vars_in_file.yml
  vars:
    upstream_value: "{{ item.replace }}"
    downstream_value: "{{ item.to }}"
    path_to_file: "{{ path_to_playbook_file }}"
  loop:
    - { replace: 'jboss_eap_home: .*$', to: "jboss_eap_home: '/opt/jboss-eap-7.4/'" }
    - { replace: 'jboss_eap_install_workdir: .*$', to: "jboss_eap_install_workdir: /opt" }
    - { replace: 'jboss_eap_archive_filename: .*$', to: "jboss_eap_archive_filename: jboss-eap-7.4.0.zip" }
    - { replace: 'jboss_eap_version: .*$', to: 'jboss_eap_version: 7.4' }
    - { replace: 'jboss_eap_enable: .*$', to: 'jboss_eap_enable: True' }
