---
- ansible.builtin.assert:
    that:
      - path_to_docs_folder is defined
      - upstream_namespace is defined
      - downstream_namespace is defined
    quiet: True
    fail_msg: "Missing required parameter."

- ansible.builtin.include_tasks: utils/check_dir_exists.yml
  vars:
    path_to_dir: "{{ path_to_docs_folder }}"

- ansible.builtin.find:
    paths: "{{ path_to_docs_folder }}"
    recurse: yes
    patterns: '*.yml,*.rst,*.md'
  register: docs

- ansible.builtin.include_tasks: docs/rename_name_and_namespace.yml
  vars:
    path_to_file: "{{ item.path }}"
  loop: "{{ docs.files }}"
