---
- assert:
    that:
      - path_to_file is defined
      - path_to_dest is defined
    quiet: true
    fail_msg: 'Missing required parameters'

- name: "Ensures {{ path_to_file }} exists."
  ansible.builtin.stat:
    path: "{{ path_to_file }}"
  register: is_path_to_file

- name: "Copy files {{ path_to_file }} to {{ path_to_dest }}"
  ansible.posix.synchronize:
    src: "{{ path_to_file }}"
    dest: "{{ path_to_dest }}"
    copy_links: yes
  when:
    - is_path_to_file.stat is defined
    - is_path_to_file.stat.exists is defined
    - is_path_to_file.stat.exists
