---
- assert:
    that:
      - src is defined
      - dest is defined
    quiet: true
    fail_msg: 'Missing required parameters'

- name: "Git clone {{ src }} to {{ dest }}"
  ansible.builtin.git:
    repo: "{{ src }}"
    dest: "{{ dest }}"
