---
- name: "Ensure required parameter(s) are provided"
  ansible.builtin.assert:
    that:
      - downstream_name is defined
    quiet: True

- name: "Determine path to corrections file."
  ansible.builtin.set_fact:
    path_to_corrections_file: "roles/janus/files/corrections/{{ downstream_name }}.yml"

- name: "Load corrections to postprocessing (if {{ path_to_corrections_file }} exists)"
  ansible.builtin.stat:
    path: "{{ path_to_corrections_file }}"
  register: corrections_file

- name: "Verify file {{ path_to_corrections_file }} metadata"
  ansible.builtin.assert:
    that:
      - corrections_file is defined
      - corrections_file.stat is defined
      - corrections_file.stat.exists is defined
    quiet: True

- block:
    - name: "Verify that path to corrections file is defined."
      ansible.builtin.assert:
        that:
          - corrections_file.stat.path is defined
        quiet: True

    - name: "Define correction vars to deal with possible exclusions in the generation process"
      ansible.builtin.include_vars:
        file: "{{ corrections_file.stat.path }}"
        name: corrections

    - name: "Set false positives var"
      ansible.builtin.set_fact:
        false_positives: "{{ corrections.false_positives }}"
  when:
      - corrections_file.stat.exists
