---
- ansible.builtin.include_tasks: roles/janus/tasks/prereqs.yml

- ansible.builtin.include_tasks: roles/janus/tasks/validations/check_required_parameters.yml

- ansible.builtin.include_tasks: roles/janus/tasks/validations/path_check.yml
  vars:
    path_to_validate: "{{ project_root_folder }}"

- ansible.builtin.include_tasks: roles/janus/tasks/collection_skeleton.yml

- ansible.builtin.include_tasks: roles/update_galaxy_yml.yml

- ansible.builtin.include_tasks: docs/main.yml
  vars:
    path_to_docs_folder: "{{ downstream_project }}/docs"

- ansible.builtin.include_tasks: roles/janus/tasks/roles/main.yml

- ansible.builtin.include_tasks: roles/janus/tasks/playbooks/main.yml
