---
- ansible.builtin.include_tasks: utils/check_dir_exists.yml
  vars:
    path_to_dir: "{{ molecule_dir }}"

- ansible.builtin.find:
    paths: "{{ molecule_dir }}"
    recurse: yes
    patterns: '*.yml'
  register: molecule_yaml

- ansible.builtin.include_tasks: utils/replace_name_and_namespace.yml
  vars:
    path_to_file: "{{ item.path }}"
  loop: "{{ molecule_yaml.files }}"
