---
false_positives:
 - match: "eap_install_workdir: /opt/eap"
   replace: "eap_install_workdir: /opt"
 - match: "eap[.]statistics-enabled"
   replace: "wildfly.statistics-enabled"
 - match: "eap-configuration:"
   replace: "wildfly-configuration:"
