---
upstream_name:
downstream_name:
upstream_collection_name: "{{ upstream_name }}"
project_git_url:
project_git_version:
upstream_namespace: middleware_automation
downstream_namespace: redhat
workdir: "{{ lookup('env', 'PWD') }}"
upstream_organisation: 'ansible-middleware'
upstream_projects_dir: "{{ workdir }}/upstream"
downstream_projects_dir: "{{ workdir }}/downstream"
skip_setup: True
post_processors_replacements: []
upstream_downstream_collections_map:
  - { upstream_name: 'redhat_csp_download', downstream_name: 'redhat_csp_download' }
  - { upstream_name: 'jws', downstream_name: 'jws' }
  - { upstream_name: 'wildfly', downstream_name: 'eap' }
  - { upstream_name: 'infinispan', downstream_name: 'data_grid' }
  - { upstream_name: 'keycloak', downstream_name: 'sso' }
  - { upstream_name: 'amq', downstream_name: 'amq_broker' }
  - { upstream_name: 'amq_streams', downstream_name: 'amq_streams' }
  - { upstream_name: 'common', downstream_name: 'runtimes_common' }