---
- import_playbook: ../janus.yml
  vars:
    upstream_name: activemq
    downstream_name: amq
    project_root_folder: "upstream/{{ upstream_name }}.git"
    project_git_url: "https://github.com/ansible-middleware/amq.git"
