---
- import_playbook: ../janus.yml
  vars:
    upstream_name: wildfly
    downstream_name: jboss_eap
    project_git_url: "https://github.com/ansible-middleware/wildfly.git"
    project_git_version: down_assets
