---
- import_playbook: ../janus.yml
  vars:
    upstream_name: jws
    downstream_name: "{{ upstream_name }}"
    project_git_url: "https://github.com/guidograzioli/jws-ansible-playbook.git"
    project_git_version: jws_validation_ds_defaults