---
- assert:
    that:
      - path_to_file is defined
    quiet: True
    fail_msg: "Missing required parameters."

- ansible.builtin.stat:
    path: "{{ path_to_file }}"
  register: is_path_to_file

- assert:
    that:
      - is_path_to_file is defined
      - is_path_to_file.stat is defined
      - is_path_to_file.stat.exists is defined
      - is_path_to_file.stat.exists
    quiet: True
    fail_msg: "Invalid path to dir: {{ path_to_file }}."
