---
- set_fact:
    upstream_value: "{{ upstream_name }}"
  when:
    - not upstream_value is defined

- set_fact:
    downstream_value: "{{ downstream_name }}"
  when:
    - not downstream_value is defined

- ansible.builtin.stat:
    path: "{{ path_to_file }}"
  register: is_path_to_file

- name: "Replace all occurences of upstream '{{ upstream_value }}' to downstream '{{ downstream_value }}' in '{{ path_to_file }}'"
  ansible.builtin.replace:
    path: "{{ path_to_file }}"
    regexp: "{{ upstream_value }}"
    replace: "{{ downstream_value }}"
    #validate: "python -c 'import yaml, sys; print(yaml.safe_load(sys.stdin))'"
  when:
    - is_path_to_file.stat.exists
    - upstream_value != downstream_value
